# Generated by Django 3.0.5 on 2023-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmodel',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='Description',
            field=models.TextField(default='fferffe', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='Price',
            field=models.IntegerField(default=5, verbose_name='price'),
            preserve_default=False,
        ),
    ]
